spring:
  application:
    name: spring-cloud-gateway

  cloud:
    gateway:
      routes:
        - predicates:
            #if request is gateway/get?name=kelvin
            - Path=/gateway/**
            - Query=name,kelvin
            - Method=get
#            - Header=key,value
#            - Cookie=token,123
            - Auth=Authorization  #need to add Authorization=XXXX to request header
          filters:
            #means remove one url prefix, that is /gateway
            - StripPrefix=1
          uri: http://localhost:8088

server:
  port: 8888

#if request:
#need to add cookie:token=123
#http://localhost:8888/gateway/get?name=kelvin
#will route to:
#http://localhost:user-service-provider-port/get



