from ubuntu:bionic
run mv /etc/apt/sources.list /etc/apt/sources.list.bak
#using aliyun ubuntu bionic sources
copy ./sources.list /etc/apt
run apt update
run apt upgrade -y
run apt install netcat -y
run apt install net-tools -y
#from xiejia
