spring:
  application:
    name: spring-cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: loadbalance_route_demo
          # spring.application.name=spring-cloud-user-provider
          uri: lb://spring-cloud-user-provider
          predicates:
            - Path=/gatewaylb/**
          filters:
            - StripPrefix=1
        - id: predicates_route_demo
          uri: http://localhost:8088/
          predicates:
            #if request is gateway/get?name=kelvin
            - Path=/gateway/**
            - Query=name,kelvin
            - Method=get
#            - Header=key,value
#            - Cookie=token,123
            - Auth=Authorization  #need to add Authorization=XXXX to request header
          filters:
            #means remove one url prefix, that is /gateway
            - StripPrefix=1
        - id: define_route
          uri: http://localhost:8088/
          predicates:
            - Path=/define/**
          filters:
            - StripPrefix=1
            - GpDefine=GP_Kelvin

#        - id: retry_route
#          uri: http://localhost:8088/
#          predicates:
#            - Path=/retry/**
#          filters:
#            - StripPrefix=1
#            - name: Retry
#              args:
#                retries: 3
#                status: 503 # when server return 503, it will retry.
#        - id: add_request_parameter_route
#          uri: http://localhost:8088/
#          filters:
#            # will add key=name, value=kelvin in header.
#            - AddRequestParameter=name,kelvin #{key,value}

            #Request rate limiter filer need to add redis dependency
#        - id: request_rateLimiter_route
#          uri: http://localhost:8088/
#          predicates:
#            - Path=/ratelimiter/**
#          filters:
#            - name: RequestRateLimiter
#              args:
##                denyEmptyKey: false
#                keyResolver: '#{@ipAddressKeyResolver}'
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 2
#            - StripPrefix=1

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"


#if request:
#need to add cookie:token=123
#http://localhost:8888/gateway/get?name=kelvin
#will route to:
#http://localhost:user-service-provider-port/get



