spring:
  application:
    name: spring-cloud-gateway-hystrix

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
#        - id: hystrix_route
#          uri: http://localhost:8088/
#          predicates:
#            - Path=/hystrix/**
#          filters:
#            - StripPrefix=1
#            #prefix of HystrixGatewayFilterFacotry
#            - name: Hystrix
#              args:
#                name: default
#                fallbackUri: 'forward:/defaultFallback'
        - id: order_route
          uri: http://localhost:8087/
          predicates:
            - Path=/gpmall/**
          filters:
            - StripPrefix=1
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*,hystrix.stream"


#if request:
#need to add cookie:token=123
#http://localhost:8888/gateway/get?name=kelvin
#will route to:
#http://localhost:user-service-provider-port/get



