@startuml
'https://plantuml.com/class-diagram

interface IPrototype{
    clone()
}


class ConcreatePrototypeA
ConcreatePrototypeA ..|>IPrototype
ConcreatePrototypeB ..|>IPrototype

circle client

client --> IPrototype


@enduml